### ISSUE TITLE
Crashes with Sodium

### ISSUE THREAD

**Issue by 2mal3** [StartsMercury/simply-no-shading#10]
Together with Sodium the game crashes at various points:
- When you click on "Options" in the title screen. -> [crash log](https://github.com/StartsMercury/simply-no-shading/files/8196378/crash-client.txt).
- When entering a world (newly created or already existing ones). -> [crash log](https://github.com/StartsMercury/simply-no-shading/files/8196446/crash-client.txt)

Fabric 0.13.3, Simpy No Shading 4.3.3 and Sodium 0.4.1.

**Comment by 2mal3** [comment]
With Simpy No Shading 4.3.5, the game no longer crashes when you click the Options button, but still crashes when you enter a world.

**Comment by StartsMercury** [comment]
Can I have a copy of the crash log?

**Comment by 2mal3** [comment]
Bug is fixed in 4.3.7
