### ISSUE TITLE
backport newer features to 1.17

### ISSUE THREAD

**Issue by justlukie** [StartsMercury/simply-no-shading#100]

**Comment by StartsMercury** [comment]
Work already started, though I wasn't able to make translatable texts work (and gave up). I might try again soon when I have the time.

**Comment by StartsMercury** [comment]
Took almost a year for me to figure out that it was a me issue ;-;. [Anyways version 6.1.0 for Minecraft 1.17.1 should be live on Modrinth now.](https://modrinth.com/mod/simply-no-shading/version/6.1.0+1.17.1) Hopefully it works outside of the dev environment.
