### ISSUE TITLE
Simply-no-shading incompatible with Sodium 0.4.9

### ISSUE THREAD

**Issue by foxdst** [StartsMercury/simply-no-shading#105]
[crash-2023-03-31_21.21.02.0360-quilt_loader.txt](https://github.com/StartsMercury/simply-no-shading/files/11119847/crash-2023-03-31_21.21.02.0360-quilt_loader.txt)

Downgrading Sodium to version 0.4.8 and mods integrated with it (Iris, Indium etc.) resolves this issue.

**Comment by StartsMercury** [comment]
6.0.4 is live for Minecraft 1.19.3. Could you please confirm if it fixed the issue?

**Comment by foxdst** [comment]
> 6.0.4 is live for Minecraft 1.19.3. Could you please confirm if it fixed the issue?

Still some incompatibility with Sodium 0.4.9

[crash-2023-04-01_08.08.01.8270-quilt_loader.txt](https://github.com/StartsMercury/simply-no-shading/files/11125187/crash-2023-04-01_08.08.01.8270-quilt_loader.txt)

**Comment by StartsMercury** [comment]
6.0.5 is live. Could you please confirm if it fixed the issue?

**Comment by StartsMercury** [comment]
6.0.5 is live for Minecraft 1.19.3. Does it fix the issue?

**Comment by foxdst** [comment]
So far everything looks to be running good with 6.0.5

No errors or crashes to report
