### ISSUE TITLE
Mod causes Minecraft to crash on M1 mac

### ISSUE THREAD

**Issue by ItsSunnyMonster** [StartsMercury/simply-no-shading#112]
I was able to verify that before installing this mod the game still does not crash. 

I have attached the crash log
[crash-2023-08-06_10.44.04-client.txt](https://github.com/StartsMercury/simply-no-shading/files/12268378/crash-2023-08-06_10.44.04-client.txt)

**Comment by StartsMercury** [comment]
Analyzing the crash log shows that you're using Simply No Shading `6.0.8` with Sodium `0.4.10`. This version of Simply No Shading is made for Sodium `0.5.0`, you should instead use `6.0.7`. Tell me then if `6.0.7` still causes a crash.

**Comment by StartsMercury** [comment]
misclick

**Comment by ItsSunnyMonster** [comment]
Thank you! That was indeed the issue, sorry for wasting your time. Closing this issue.
