### ISSUE TITLE
Be able to disable entity shadow

### ISSUE THREAD

**Issue by Minecrafthyr** [StartsMercury/simply-no-shading#113]
As you see in the title, this is an enhancement issue. 
The entity like item frame is really sharp compared to other blocks.

**Comment by Minecrafthyr** [comment]
Change `minecraft/shaders/include/light.glsl` can disable entity shadow and item model shadow.
![image](https://github.com/StartsMercury/simply-no-shading/assets/107340726/974a6a85-4e9a-4739-b2c0-494e346e5db4)

**Comment by StartsMercury** [comment]
"I'd say this is a vast improvement." Anyways, I might look into ways to not apply it to everything all at once. For now, I think it can be an "experimental" resource pack that's available with the mod. (Yeah, it actually got rid of any shading that wasn't covered by the mod it seems)
![2023-10-29_18 00 47](https://github.com/StartsMercury/simply-no-shading/assets/89975834/961377e0-b2e7-48a2-9808-fc450d9cfc1e)

**Comment by StartsMercury** [comment]
This feature will be stable in the upcoming v7.4.0 release.
