### ISSUE TITLE
How do I disable shading on 1 specific item?

### ISSUE THREAD

**Issue by realFusionFusion** [StartsMercury/simply-no-shading#119]
What do I change in the GLSL file from the mod's resource pack so that it only applies to totems of undying? It's so that it becomes easier to _instantly_ tell whether your off-hand is holding a totem or not for PvP.

**Comment by StartsMercury** [comment]
Hello and sorry I took the time to *not* reply immediately! I didn't know how at the time to achieve this but I did consider looking into it, and I did find out how. Though it certainly is possible in the one method I know, I didn't think it would "fit" in this mod, Simply No Shading, but I did have it as a separate mod, [Totem No Shading](https://modrinth.com/mod/totem-no-shading).

**Comment by realFusionFusion** [comment]
Thank you! It's okay don't worry about it. Really appreciate the help man
