### ISSUE TITLE
[Feature] Items in the inventory are no longer shaded.

### ISSUE THREAD

**Issue by seriousfreezing** [StartsMercury/simply-no-shading#120]
Well, I'm trying to find a mod that makes a feature similar to how [Bedrock works. ](https://bugs.mojang.com/browse/MCPE-7311)

And what would that be? Good blocks/items that produce light are not shaded in the inventory. So I was wondering if I could have this feature just for the inventory, or maybe just for some inventory items too. Idk

**Comment by StartsMercury** [comment]
I have made this a separate mod: https://modrinth.com/mod/luminous-no-shading

I uploaded it to Modrinth so it is still being reviewed, but could you check if it is already approved and available? It currently only supports 1.20.1 and some things may not work with other mods, such as Sodium, which replaces the rendering (so some things are not affected). I will update this comment if I notice it is approved on Modrinth.

**Comment by seriousfreezing** [comment]
I'm happy with this news, I'll wait for it to be stable enough to put in my 1.21 modpack!
