### ISSUE TITLE
Minecraft crashes when join the nether/end dimension (1.20.1)

### ISSUE THREAD

**Issue by necromancertype** [StartsMercury/simply-no-shading#121]
Tried specific ways to fix - nothing helped but disabling the mod
Here is crash report https://mclo.gs/mWqCrUF
I will be thankful for any help

**Comment by N1zyx3** [comment]
Couldn't find a fix?

**Comment by necromancertype** [comment]
> Couldn't find a fix?

No

**Comment by StartsMercury** [comment]
Hi! It took me a while to have a chance to try fixing it. Testing says it's fixed but I wanted to know if it's truly fixed in this release here:

<https://modrinth.com/mod/simply-no-shading/version/7.4.0+mc1.20.1>

**Comment by N1zyx3** [comment]
> Hi! It took me a while to have a chance to try fixing it. Testing says it's fixed but I wanted to know if it's truly fixed in this release here:
> 
> https://modrinth.com/mod/simply-no-shading/version/7.4.0+mc1.20.1

Thanks!

**Comment by necromancertype** [comment]
> Hi! It took me a while to have a chance to try fixing it. Testing says it's fixed but I wanted to know if it's truly fixed in this release here:
> 
> https://modrinth.com/mod/simply-no-shading/version/7.4.0+mc1.20.1

hello, yes, it is indeed fixed! I have just tried it, thank you for your work!
<3
