### ISSUE TITLE
Images on Modrinth and Curseforge pages fail loading (HTTP 404)

### ISSUE THREAD

**Issue by James103** [StartsMercury/simply-no-shading#62]
The images on the Modrinth and Curseforge project pages for this mod are not loading because the source URL still references the branch `main` of this repository, but that branch has been renamed to `4.x/1.18.2`. This broke these links, causing them to return HTTP 404.

To fix this, the links to the images in both the Modrinth and Curseforge pages should be updated to reflect the new branch name.

**Comment by StartsMercury** [comment]
Fixed 👍
