### ISSUE TITLE
Toggle Hand Held Item Shading

### ISSUE THREAD

**Issue by Xrey274** [StartsMercury/simply-no-shading#8]
I'd like to remove the "directional" shadow of items in hand (idk what else to call it, look at images below)
![2022-01-31_19 34 05](https://user-images.githubusercontent.com/30723811/151844059-6ebbd57f-380d-4618-9f8e-e836448790be.png)
![2022-01-31_19 34 17](https://user-images.githubusercontent.com/30723811/151844068-9311571e-51ae-4254-954b-a053a5bbb8c9.png)
.

**Comment by StartsMercury** [comment]
~Thanks for the suggestion, implementation will be in due time.~

Thank you for your suggestion! It would be implemented once I'm done with everything else; I would probably have to deal with core shaders :eyes:

**Comment by realFusionFusion** [comment]
I was gonna suggest this, thank you for considering it! I would also like to suggest an option to be able to choose which items you want this to apply to.

**Comment by StartsMercury** [comment]
This feature will, finally, be stable in the upcoming v7.4.0 release. This is included in the Entity Shading toggle.

**Comment by Xrey274** [comment]
Wow I had forgotten about this issue, it's been 2 years lol.
