### ISSUE TITLE
Does It Fix the Anti-aliasing Problems for OptiFine?

### ISSUE THREAD

**Issue by Nukecraft5419** [StartsMercury/simply-no-shading#84]
![2022-10-30_05 42 13](https://user-images.githubusercontent.com/72621737/198863089-9bcf2278-7131-4472-bbc4-da6c7e53be30.png)

**Comment by StartsMercury** [comment]
May I know what problem(s) you are trying to solve with this mod installed? May I know what improvements your were looking for?

**Comment by StartsMercury** [comment]
If you were expecting to increase performance compared to Vanilla, then tough luck, it would only be reasonable to use OptiFine Internal Shaders if you don't mind the decrease in performance. This mod offers the same but **less** impact on performance.

**Comment by Nukecraft5419** [comment]
I thought the mod solved the anti-aliasing problems that optifine usually already has built-in

**Comment by StartsMercury** [comment]
I see. Yeah, anti-aliasing is not in the scope of this mod.

**Comment by Nukecraft5419** [comment]
Do you know any mods that do this and don't give a problem with Sodium?

**Comment by StartsMercury** [comment]
Sorry, I don't know...
