### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by 2mal3** [StartsMercury/simply-no-shading#9]
The game crashes immediately when you start it with the mod, even without other mods.
Fabric version 0.13.3 and mod version 4.1.18. Everything else should be in the [crash log](https://github.com/StartsMercury/simply-no-shading/files/8185827/crash-client.txt).

**Comment by StartsMercury** [comment]
I haven't encountered the crash (maybe because I'm testing in a development environment),
but If you don't mind testing with the newer alpha version of the mod and seeing if it no longer crashes.

**Comment by 2mal3** [comment]
Still the same crash with 4.2.2

**Comment by 2mal3** [comment]
With the 4.2.9 the game no longer crashes 👍
